# These are all the cops that are disabled in the default configuration.

# This file was originally derived from
# https://raw.githubusercontent.com/saks/rubocop_configs/master/rubocop/disabled.yml

NegatedIf:
  Description: >
                 Favor unless over if for negative conditions
                 (or control flow or).
  Enabled: false


Layout/SpaceInsideBrackets:
  Description: 'No spaces after [ or before ].'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-spaces-braces'
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Description: 'No unnecessary spaces inside delimiters of %i/%w/%x literals.'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

